# Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: quay.io/gnunn/server@sha256:69f513a0a4df3afd4f4036eab1ea3573d4eacc2862eb150a675d01e4f8bcd981
          ports:
            - containerPort: 80
